/*
** filter_chain.cpp
**
** Visual filter post-processing chain for Runestone.
*/

#include "filter_chain.h"
#include "debugwriter.h"
#include "glstate.h"
#include "sharedstate.h"
#include "filesystem/filesystem.h"
#include "util/encoding.h"

#include <sys/stat.h>
#include <cstring>
#include <cmath>

// ── Embedded shader sources (generated by make_xxd.sh) ──────────
#ifndef MKXPZ_BUILD_XCODE
#include "filterQuad.vert.xxd"
#include "filterPassthrough.frag.xxd"
#include "filterBrightnessContrast.frag.xxd"
#include "filterSharpBilinear.frag.xxd"
#include "filterSharpen.frag.xxd"
#endif

#define SHADER_SRC(name) shader_##name, shader_##name##_len

// ── FilterShader ─────────────────────────────────────────────────

FilterShader::FilterShader() : program(0), vertShader(0), fragShader(0) {}

FilterShader::~FilterShader() {
    if (program) {
        gl.DeleteProgram(program);
    }
    if (vertShader) gl.DeleteShader(vertShader);
    if (fragShader) gl.DeleteShader(fragShader);
}

bool FilterShader::compile(const char *vertSrc, int vertLen,
                           const char *fragSrc, int fragLen,
                           const char *name) {
    vertShader = gl.CreateShader(GL_VERTEX_SHADER);
    fragShader = gl.CreateShader(GL_FRAGMENT_SHADER);
    program = gl.CreateProgram();

    // Prepare source arrays with common header
    static const char glesDefine[] = "#define GLSLES\n";
    static const char fragDefine[] = "#define FRAGMENT_SHADER\n";

    // Vertex shader
    {
        const GLchar *srcs[3];
        GLint sizes[3];
        int i = 0;
        if (gl.glsles) { srcs[i] = glesDefine; sizes[i] = sizeof(glesDefine)-1; i++; }
        srcs[i] = (const GLchar*)shader_filterQuad_vert; sizes[i] = 0; i++; // placeholder
        srcs[i] = (const GLchar*)vertSrc; sizes[i] = vertLen; i++;
        // Actually, we need the common header. Let's use the shader_common from the build.
        // For filter shaders, we prepend our own precision since we're standalone.
        std::string header = gl.glsles ?
            "#ifdef FRAGMENT_SHADER\nprecision mediump float;\n#endif\n" :
            "#define highp\n#define mediump\n#define lowp\n";

        const GLchar *finalSrcs[4];
        GLint finalSizes[4];
        int j = 0;
        if (gl.glsles) { finalSrcs[j] = glesDefine; finalSizes[j] = sizeof(glesDefine)-1; j++; }
        finalSrcs[j] = header.c_str(); finalSizes[j] = header.size(); j++;
        finalSrcs[j] = (const GLchar*)vertSrc; finalSizes[j] = vertLen; j++;

        gl.ShaderSource(vertShader, j, finalSrcs, finalSizes);
    }

    gl.CompileShader(vertShader);
    GLint success;
    gl.GetShaderiv(vertShader, GL_COMPILE_STATUS, &success);
    if (!success) {
        char log[512];
        gl.GetShaderInfoLog(vertShader, sizeof(log), 0, log);
        Debug() << "FilterShader: vertex compile failed (" << name << "):" << log;
        return false;
    }

    // Fragment shader
    {
        std::string header = gl.glsles ?
            "#define GLSLES\n#ifdef FRAGMENT_SHADER\nprecision mediump float;\n#endif\n" :
            "#define highp\n#define mediump\n#define lowp\n#define FRAGMENT_SHADER\n";

        const GLchar *finalSrcs[2];
        GLint finalSizes[2];
        finalSrcs[0] = header.c_str(); finalSizes[0] = header.size();
        finalSrcs[1] = (const GLchar*)fragSrc; finalSizes[1] = fragLen;

        gl.ShaderSource(fragShader, 2, finalSrcs, finalSizes);
    }

    gl.CompileShader(fragShader);
    gl.GetShaderiv(fragShader, GL_COMPILE_STATUS, &success);
    if (!success) {
        char log[512];
        gl.GetShaderInfoLog(fragShader, sizeof(log), 0, log);
        Debug() << "FilterShader: fragment compile failed (" << name << "):" << log;
        return false;
    }

    gl.AttachShader(program, vertShader);
    gl.AttachShader(program, fragShader);

    // Bind standard attribute locations (matching mkxp-z convention)
    gl.BindAttribLocation(program, 0, "position");
    gl.BindAttribLocation(program, 1, "texCoord");
    gl.BindAttribLocation(program, 2, "color");

    gl.LinkProgram(program);
    gl.GetProgramiv(program, GL_LINK_STATUS, &success);
    if (!success) {
        char log[512];
        gl.GetProgramInfoLog(program, sizeof(log), 0, log);
        Debug() << "FilterShader: link failed (" << name << "):" << log;
        return false;
    }

    Debug() << "FilterShader: compiled" << name;
    return true;
}

void FilterShader::bind() {
    glState.program.set(program);
}

GLint FilterShader::getUniformLoc(const char *name) {
    auto it = uniformCache.find(name);
    if (it != uniformCache.end()) return it->second;
    GLint loc = gl.GetUniformLocation(program, name);
    uniformCache[name] = loc;
    return loc;
}

void FilterShader::setUniform(const char *name, float value) {
    GLint loc = getUniformLoc(name);
    if (loc >= 0) gl.Uniform1f(loc, value);
}

void FilterShader::setUniform(const char *name, float x, float y) {
    GLint loc = getUniformLoc(name);
    if (loc >= 0) gl.Uniform2f(loc, x, y);
}

void FilterShader::setUniform(const char *name, int value) {
    GLint loc = getUniformLoc(name);
    if (loc >= 0) gl.Uniform1i(loc, value);
}

void FilterShader::applyViewportProj(int width, int height) {
    // Same ortho projection as ShaderBase
    const float a = 2.f / width;
    const float b = 2.f / height;
    const float c = -2.f;
    GLfloat mat[16] = {
        a,  0,  0,  0,
        0,  b,  0,  0,
        0,  0,  c,  0,
       -1, -1, -1,  1
    };
    GLint loc = getUniformLoc("projMat");
    if (loc >= 0) gl.UniformMatrix4fv(loc, 1, GL_FALSE, mat);

    // texSizeInv = 1.0 / size
    loc = getUniformLoc("texSizeInv");
    if (loc >= 0) gl.Uniform2f(loc, 1.f / width, 1.f / height);

    // translation = 0
    loc = getUniformLoc("translation");
    if (loc >= 0) gl.Uniform2f(loc, 0.f, 0.f);
}

// ── FilterChain ──────────────────────────────────────────────────

FilterChain::FilterChain()
    : initialized(false), bufferW(0), bufferH(0), lastModTime(0),
      quadVBO(0) {
    TEXFBO::clear(pingPong[0]);
    TEXFBO::clear(pingPong[1]);
}

FilterChain::~FilterChain() {
    if (initialized) {
        TEXFBO::fini(pingPong[0]);
        TEXFBO::fini(pingPong[1]);
    }
    if (quadVBO) gl.DeleteBuffers(1, &quadVBO);
}

void FilterChain::initQuad() {
    // Fullscreen quad: 4 vertices, 2 triangles
    // Position covers [-1,1], tex coords cover [0,1]
    static const float vertices[] = {
        // pos        // tex
        -1.f, -1.f,   0.f, 0.f,
         1.f, -1.f,   1.f, 0.f,
         1.f,  1.f,   1.f, 1.f,
        -1.f,  1.f,   0.f, 1.f,
    };
    static const unsigned short indices[] = { 0, 1, 2, 0, 2, 3 };

    gl.GenBuffers(1, &quadVBO);
    gl.BindBuffer(GL_ARRAY_BUFFER, quadVBO);
    gl.BufferData(GL_ARRAY_BUFFER, sizeof(vertices), vertices, GL_STATIC_DRAW);

    // Store index data in a separate IBO
    GLuint ibo;
    gl.GenBuffers(1, &ibo);
    gl.BindBuffer(GL_ELEMENT_ARRAY_BUFFER, ibo);
    gl.BufferData(GL_ELEMENT_ARRAY_BUFFER, sizeof(indices), indices, GL_STATIC_DRAW);

    gl.BindBuffer(GL_ARRAY_BUFFER, 0);
    gl.BindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0);
}

void FilterChain::drawQuad() {
    gl.BindBuffer(GL_ARRAY_BUFFER, quadVBO);

    // position (location 0)
    gl.EnableVertexAttribArray(0);
    gl.VertexAttribPointer(0, 2, GL_FLOAT, GL_FALSE, 4 * sizeof(float), (void*)0);

    // texCoord (location 1)
    gl.EnableVertexAttribArray(1);
    gl.VertexAttribPointer(1, 2, GL_FLOAT, GL_FALSE, 4 * sizeof(float), (void*)(2 * sizeof(float)));

    gl.DrawArrays(GL_TRIANGLE_FAN, 0, 4);

    gl.DisableVertexAttribArray(0);
    gl.DisableVertexAttribArray(1);
    gl.BindBuffer(GL_ARRAY_BUFFER, 0);
}

void FilterChain::ensureBuffers(int w, int h) {
    if (w == bufferW && h == bufferH) return;

    if (initialized) {
        TEXFBO::fini(pingPong[0]);
        TEXFBO::fini(pingPong[1]);
    }

    for (int i = 0; i < 2; i++) {
        TEXFBO::init(pingPong[i]);
        TEXFBO::allocEmpty(pingPong[i], w, h);
        TEXFBO::linkFBO(pingPong[i]);
    }

    bufferW = w;
    bufferH = h;
    initialized = true;
}

FilterConfig FilterChain::parseConfig(const json5pp::value &json) {
    FilterConfig cfg;
    cfg.enabled = false;

    if (!json.is_object()) return cfg;

    auto &obj = json.as_object();

    cfg.enabled = obj["enabled"].as_boolean();
    cfg.preset = obj.count("preset") ? obj["preset"].as_string() : "unknown";
    cfg.aspectMode = obj.count("aspectMode") ? obj["aspectMode"].as_string() : "fit_4_3";

    if (obj.count("passes") && obj["passes"].is_array()) {
        auto &passes = obj["passes"].as_array();
        for (auto &p : passes) {
            if (!p.is_object()) continue;
            auto &pObj = p.as_object();
            FilterPassConfig pass;
            pass.shader = pObj["shader"].as_string();
            if (pObj.count("params") && pObj["params"].is_object()) {
                auto &params = pObj["params"].as_object();
                for (auto &kv : params) {
                    if (kv.second.is_number()) {
                        pass.params[kv.first] = kv.second.as_number();
                    }
                }
            }
            cfg.passes.push_back(pass);
        }
    }

    return cfg;
}

bool FilterChain::loadConfig(const char *path) {
    if (!mkxp_fs::fileExists(path)) {
        config.enabled = false;
        return false;
    }

    try {
        std::string contents = mkxp_fs::contentsOfFileAsString(path);
        auto json = json5pp::parse5(contents);
        config = parseConfig(json);
        Debug() << "FilterChain: loaded config, enabled=" << config.enabled
                << ", preset=" << config.preset
                << ", passes=" << config.passes.size();
        return config.enabled;
    } catch (const std::exception &e) {
        Debug() << "FilterChain: failed to parse config:" << e.what();
        config.enabled = false;
        return false;
    }
}

bool FilterChain::checkForUpdate(const char *path) {
    struct stat st;
    if (stat(path, &st) != 0) return false;
    if (st.st_mtime > lastModTime) {
        lastModTime = st.st_mtime;
        loadConfig(path);
        return true;
    }
    return false;
}

bool FilterChain::compileShader(FilterShader &shader, const char *name) {
    // Map shader names to embedded sources
    struct ShaderEntry {
        const unsigned char *vert;
        int vertLen;
        const unsigned char *frag;
        int fragLen;
    };

    // All filter shaders use the same vertex shader
    static const unsigned char *vertSrc = filterQuad_vert;
    static int vertLen = filterQuad_vert_len;

    const unsigned char *fragSrc = nullptr;
    int fragLen = 0;

    if (strcmp(name, "passthrough") == 0) {
        fragSrc = filterPassthrough_frag; fragLen = filterPassthrough_frag_len;
    } else if (strcmp(name, "brightness_contrast") == 0) {
        fragSrc = filterBrightnessContrast_frag; fragLen = filterBrightnessContrast_frag_len;
    } else if (strcmp(name, "sharp_bilinear") == 0) {
        fragSrc = filterSharpBilinear_frag; fragLen = filterSharpBilinear_frag_len;
    } else if (strcmp(name, "sharpen") == 0) {
        fragSrc = filterSharpen_frag; fragLen = filterSharpen_frag_len;
    } else {
        Debug() << "FilterChain: unknown shader" << name;
        return false;
    }

    return shader.compile((const char*)vertSrc, vertLen,
                          (const char*)fragSrc, fragLen, name);
}

TEXFBO &FilterChain::execute(TEXFBO &source, int sourceW, int sourceH,
                             int outputW, int outputH) {
    if (!isEnabled()) return source;

    ensureBuffers(outputW, outputH);

    if (!quadVBO) initQuad();

    // Ensure all required shaders are compiled
    for (auto &pass : config.passes) {
        if (shaders.find(pass.shader) == shaders.end()) {
            FilterShader shader;
            if (compileShader(shader, pass.shader.c_str())) {
                shaders[pass.shader] = std::move(shader);
            } else {
                // Compile passthrough as fallback
                if (shaders.find("passthrough") == shaders.end()) {
                    FilterShader fallback;
                    if (compileShader(fallback, "passthrough")) {
                        shaders["passthrough"] = std::move(fallback);
                    }
                }
            }
        }
    }

    // Disable blending for filter passes
    glState.blend.pushSet(false);

    int srcIdx = 0; // Start reading from source

    for (size_t i = 0; i < config.passes.size(); i++) {
        auto &pass = config.passes[i];
        auto it = shaders.find(pass.shader);
        if (it == shaders.end()) continue; // Skip if compile failed

        FilterShader &shader = it->second;

        // Determine destination FBO
        int dstIdx = (i + 1) % 2;
        TEXFBO &dst = pingPong[dstIdx];

        // Bind destination FBO
        FBO::bind(dst.fbo);
        glState.viewport.set(IntRect(0, 0, outputW, outputH));
        FBO::clear();

        // Bind shader
        shader.bind();
        shader.applyViewportProj(outputW, outputH);

        // Set source texture
        TEX::ID srcTex;
        if (i == 0) {
            srcTex = source.tex;
        } else {
            srcTex = pingPong[srcIdx].tex;
        }
        gl.ActiveTexture(GL_TEXTURE0);
        gl.BindTexture(GL_TEXTURE_2D, srcTex.gl);
        shader.setUniform("texture", 0);

        // Set common uniforms
        shader.setUniform("sourceSize", (float)sourceW, (float)sourceH);
        shader.setUniform("outputSize", (float)outputW, (float)outputH);
        shader.setUniform("texelSize", 1.f / outputW, 1.f / outputH);

        // Set pass-specific parameters
        for (auto &kv : pass.params) {
            shader.setUniform(kv.first.c_str(), kv.second);
        }

        // Draw fullscreen quad
        drawQuad();

        srcIdx = dstIdx;
    }

    glState.blend.pop();

    // Return the last written buffer
    return pingPong[srcIdx];
}
